networks:
  smq-bridge:
    driver: bridge

services:
  smq-spring-server:
    container_name: smq-spring-server
    build:
      dockerfile: server.Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      - smq-bridge
    command: [ "java", "-jar", "/app/server.jar" ]